[build]
  command = "npm run build"
  publish = "dist/client"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/bare/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/wisp/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/adblock/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp", "bufferutil", "utf-8-validate"]
  included_files = ["dist/**"]

[dev]
  command = "npm run dev"
  port = 4321
  targetPort = 8080
  autoLaunch = false
